version: "3.3"

services:
  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.4
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.4
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  logstash:
    build:
      context: logstash/.
    depends_on:
      - elasticsearch
#    volumes:
#      - type: bind
#        source: ./pipeline/
#        target: /usr/share/logstash/pipeline/
#      - type: bind
#        source: ./settings/
#        target: /usr/share/logstash/config/

  test-filebeat:
    build:
      context: test-filebeat/.
    volumes:
      - type: bind
        source: ./logs/
        target: /var/beats_logs/

volumes:
  esdata:
