version: "3.3"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.4
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  logstash:
    image: docker.elastic.co/logstash/logstash:5.6.4
    depends_on:
      - elasticsearch
#    volumes:
#      - type: bind
#        source: ./pipeline/
#        target: /usr/share/logstash/pipeline/
#      - type: bind
#        source: ./settings/
#        target: /usr/share/logstash/config/

  kibana:
    build:
      context: kibana/.
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"

volumes:
  esdata:
